export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const GET_ALL_APP = 'GET_ALL_APP'
export const GET_ALL_AUTH = 'GET_ALL_AUTH'
export const GET_ALL_ROLE = 'GET_ALL_ROLE'
export const GET_ALL_USER = 'GET_ALL_USER'
export const GET_ALL_ALGORITHM = 'GET_ALL_ALGORITHM'
export const GET_ALL_MODEL = 'GET_ALL_MODEL'
export const GET_ALL_STRATEGY = 'GET_ALL_STRATEGY'
export const GET_ALL_INFO = 'GET_ALL_INFO'
